# Generated by Django 4.0.6 on 2022-08-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0004_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publ_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Publ_house name')),
            ],
        ),
    ]
