# Generated by Django 4.0.6 on 2022-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0004_publ_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Series description'),
        ),
    ]
