# Generated by Django 4.0.6 on 2022-08-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0005_series_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Book's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Book's description")),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='rosters.book', verbose_name='Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='rosters.book', verbose_name='Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publ_house',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='publs', to='rosters.book', verbose_name='Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='rosters.book', verbose_name='Book'),
            preserve_default=False,
        ),
    ]
