# Generated by Django 4.0.6 on 2022-08-22 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0007_book_author_book_publishing_book_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='rosters.author', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
