# Generated by Django 4.0.6 on 2022-08-22 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0008_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='rosters.genre', verbose_name='Genre'),
            preserve_default=False,
        ),
    ]
